// Generated by packages/design/nm-components from NoMercy.Plugins.Abstractions. Do not edit.
//
// The server decides these words. Written by hand here once, this list said
// movies, shows and tools while the server placed music, video, library,
// dashboard, settings and addon, so every section keyed on the three was
// empty on every server and a plugin drew no navigation at all.

/**
 * What a plugin is, which decides where its screens live.
 * A plugin never invents a path. It says what it is, and the kind decides the
 * prefix on every platform, so the same plugin lands in the music area on the
 * web, on a phone and on a television without any of them agreeing on anything
 * beyond this word. A plugin that could name its own route would collide with
 * the app's own pages, and no client could route a plugin it had never seen.
 */
export const PluginKind = {
	Music: 'music',
	Video: 'video',
	Library: 'library',
	Dashboard: 'dashboard',
	Settings: 'settings',
	Addon: 'addon',
} as const;

export type PluginKindValue = typeof PluginKind[keyof typeof PluginKind];

/**
 * What a client does when the user activates a component. Named for the same
 * reason as PluginComponentType: an unrecognised type is a
 * silent no-op on both clients.
 */
export const PluginActionType = {
	PlayMedia: 'playMedia',
	Enqueue: 'enqueue',
	Navigate: 'navigate',
	CallPlugin: 'callPlugin',
	OpenWebView: 'openWebView',
	RefreshView: 'refreshView',
	SubmitForm: 'submitForm',
	PickFile: 'pickFile',
	PickFolder: 'pickFolder',
} as const;

export type PluginActionTypeValue = typeof PluginActionType[keyof typeof PluginActionType];

/**
 * What a caller may do with a plugin.
 * The server answers this once per user per plugin and every client obeys it.
 * A caller with none never reaches the plugin: the request is refused before
 * dispatch, so the client filter is the second line rather than the first.
 */
export const PluginAccess = {
	Owned: 'owned',
	Shared: 'shared',
	None: 'none',
} as const;

export type PluginAccessValue = typeof PluginAccess[keyof typeof PluginAccess];

/**
 * What a caller needs to open one route of a plugin.
 * Coarser than PluginAccess on purpose: a plugin is owned, shared or out of
 * reach, and within a plugin somebody can see a route only the owner may use.
 * The server hides an owner route from a member before the client sees it,
 * because offering a page that answers 403 is worse than not offering it.
 */
export const PluginRouteAccess = {
	Shared: 'shared',
	Owner: 'owner',
} as const;

export type PluginRouteAccessValue = typeof PluginRouteAccess[keyof typeof PluginRouteAccess];

/**
 * Where inside a kind a placement lands.
 * A plugin says which kind it is and which slot it wants; the client owns the
 * drawing. Without slots every placement was a navigation entry, so a plugin
 * that belonged on the music home page could only add a sidebar link.
 */
export const PluginSlot = {
	Nav: 'nav',
	HomeRow: 'home-row',
	ArtistTab: 'artist-tab',
	AlbumTab: 'album-tab',
	PlayerPanel: 'player-panel',
	DetailTab: 'detail-tab',
	Live: 'live',
	Guide: 'guide',
	ChannelStrip: 'channel-strip',
	LibraryCard: 'library-card',
	Card: 'card',
	Section: 'section',
	Home: 'home',
} as const;

export type PluginSlotValue = typeof PluginSlot[keyof typeof PluginSlot];

/**
 * The host-owned management area every plugin has at {prefix}/{id}/_/...
 * The plugin never renders these pages. What a plugin is allowed, what it
 * costs, how to remove it and whether it is healthy are answers the owner has
 * to be able to trust, and an answer drawn by the thing being asked about is
 * not one.
 */
export const PluginBasePathPage = {
	Info: 'info',
	Permissions: 'permissions',
	Settings: 'settings',
	Update: 'update',
	Remove: 'remove',
	Docs: 'docs',
	License: 'license',
	Health: 'health',
} as const;

export type PluginBasePathPageValue = typeof PluginBasePathPage[keyof typeof PluginBasePathPage];

/**
 * Which kind of screen is asking.
 * The same three names the components already use, so a plugin branching on the
 * surface and a component hiding itself on one are talking about the same
 * thing. A fourth vocabulary here would mean a plugin could target a surface
 * that no component could hide from.
 */
export const PluginSurface = {
	Web: 'web',
	Mobile: 'mobile',
	Tv: 'tv',
} as const;

export type PluginSurfaceValue = typeof PluginSurface[keyof typeof PluginSurface];

/**
 * How the caller is driving this surface.
 * A form that works with a mouse is unusable with a remote, so the view
 * declares what it needs and the client says what it has. Neither guesses
 * from the screen size: a phone on a television stand is still touch, and a
 * browser on a television is still a remote.
 */
export const PluginInputDevice = {
	Pointer: 'pointer',
	Touch: 'touch',
	Remote: 'remote',
} as const;

export type PluginInputDeviceValue = typeof PluginInputDevice[keyof typeof PluginInputDevice];

/**
 * What a live player can be asked to do, by any client, for any plugin channel.
 * A tuner plugin supplies channels; it does not supply a remote control. These
 * are the buttons the host already draws, so a channel from a plugin behaves
 * like a channel from anywhere else on every client at once.
 */
export const PluginLiveAction = {
	ChannelUp: 'channel-up',
	ChannelDown: 'channel-down',
	ChannelNumber: 'channel-number',
	LastChannel: 'last-channel',
	MiniGuide: 'mini-guide',
	JumpToLive: 'jump-to-live',
	StartOver: 'start-over',
	Record: 'record',
	Quality: 'quality',
} as const;

export type PluginLiveActionValue = typeof PluginLiveAction[keyof typeof PluginLiveAction];
/**
 * Which slots each kind offers.
 * A screen reserves the space before any plugin is seen, so the grouping has
 * to be known in advance. One source, because four hand-written copies is how
 * a placement lands somewhere its author never asked for.
 */
export const PluginSlotsByKind = {
	music: ['nav', 'home-row', 'artist-tab', 'album-tab', 'player-panel'],
	video: ['nav', 'home-row', 'detail-tab', 'player-panel', 'live', 'guide', 'channel-strip'],
	library: ['nav', 'home-row', 'library-card'],
	dashboard: ['nav', 'card'],
	settings: ['section'],
	addon: ['nav', 'home'],
} as const;
